name: Publish MAUI

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (e.g. 1.2.3)"
        required: true
        type: string
env:
  CSPROJ_PATH: "src/Memory.Tester.Maui/Memory.Tester.Maui.csproj"
  DOTNET_VERSION: "10.0.x"
  WINUI_TFM: "net10.0-windows10.0.19041.0"
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # For WinUI builds
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Install MAUI workloads
        run: dotnet workload install maui --source https://api.nuget.org/v3/index.json

      - name: Restore NuGet packages
        run: dotnet restore ${{env.CSPROJ_PATH}}

      - name: Update MAUI manifest version
        shell: pwsh
        run: |
          $manifestPath = "src/Memory.Tester.Maui/Platforms/Windows/Package.appxmanifest"
          [xml]$xml = Get-Content $manifestPath
          $xml.Package.Identity.Version = "${{ github.event.inputs.version }}.0"
          $xml.Save($manifestPath)

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Decode PFX certificate
        shell: pwsh
        run: |
          $bytes = [System.Convert]::FromBase64String("${{ secrets.PFX_FILE }}")
          Set-Content -Path signingCert.pfx -Value $bytes -AsByteStream

      - name: Publish MSIX
        run: dotnet publish ${{env.CSPROJ_PATH}} -f ${{env.WINUI_TFM}} -p:PublishProfile=MSIX-win-x64.pubxml -p:PackageCertificateKeyFile=signingCert.pfx -p:PackageCertificatePassword=${{ secrets.PFX_PASSWORD }}

      - name: Find MSIX output
        id: msix
        shell: pwsh
        run: |
          $file = Get-ChildItem -Recurse -Filter *.msix | Select-Object -First 1
          if (-not $file) { throw "No MSIX file found." }
          echo "path=$($file.FullName)" >> $env:GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ github.event.inputs.version }}"
          name: "Release v${{ github.event.inputs.version }}"
          files: ${{ steps.msix.outputs.path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
